name: Create Boilerplate by Bash Steps
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The updated registry version number.'
        required: true
  # 開發階段方便用
  push:
    branch:
      - steps

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Walk through steps 👣
        run: |
          ./steps.bash boilerplate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: boilerplate
